version: '3.8'
services:
  php-apache:
    container_name: sem-keyword_php-apache
    build:
      dockerfile: Dockerfile.dev
    image: sem-keyword-webserver:dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./project:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public/
  database:
    container_name: sem-keyword_maria-db
    image: mariadb
    volumes:
      - sem-keyword-db-pers:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: i_am_root
      MYSQL_DATABASE: db01
      MYSQL_USER: db01
      MYSQL_PASSWORD: pass01
  phpmyadmin:
    container_name: sem-keyword_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - 8081:80
      - 8444:443
    depends_on:
      - database
volumes:
  sem-keyword-db-pers: