api_platform:
    defaults:
        #Pagination is disabled to reduce complexity. 
        #Might be a good idea when importing a lot of keywords
        pagination_enabled: false 
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
